@startuml

class Shape
{
    + Area
    + virtual CalculateArea()   
}

class Triangle
{
    - base
    - height
    + override CalculateArea()   
}

class Rectangle
{
    - height
    + override CalculateArea()   
}

class Square
{
     - width
    + override CalculateArea()   
}

Shape <|-- Triangle
Shape <|-- Square
Square <|-- Rectangle
@enduml